name: Bug report
description: Report a reproducible issue
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill in all required fields.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the problem
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Tell us exactly how to trigger the issue
      placeholder: |
        1. …
        2. …
        3. …
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: |
        - OS:
        - Node version:
        - Browser (if applicable):
        - Other:
